site_name: PR1 Dokumentation
theme:
  name: material
  custom_dir: overrides
  palette:
    primary: grey
  language: de
  features:
    - navigation.sections
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - extra_javascripts/extra.js
markdown_extensions:
  - pymdownx.magiclink:
      repo_url_shorthand: true
  - attr_list
  - markdown.extensions.toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify { kwds: { case: lower } }
      permalink: "\ue157"
