site_name: PR1 Dokumentation
site_author: BD
repo_url: https://github.com/bdwebnet/pr1_doku
edit_uri: edit/main/docs
theme:
  font: false
  name: material
  custom_dir: overrides
  palette:
    primary: grey
  language: de
  features:
    - navigation.sections
    - content.code.annotate
    - navigation.tabs
extra_css:
  - stylesheets/extra.css
  - stylesheets/roboto.css
extra_javascript:
  - javascripts/extra.js
  - javascripts/mathjax.js
  - javascripts/polyfill.min.js
  - javascripts/tex-mml-chtml.js
markdown_extensions:
  - pymdownx.magiclink:
      repo_url_shorthand: true
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true

