site_name: PR1 Dokumentation
site_author: BD & GreenM4x

nav:
  - index.md
  - Eingabe:
      - Scanner: eingabe/scanner.md
  - Verarbeitung:
      - Arrays: verarbeitung/arrays.md
      - Datentypen: verarbeitung/datentypen.md
      - Rechnen: verarbeitung/rechnen.md
      - Schleifen: verarbeitung/schleifen.md
  - Ausgabe:
      - Formatierung: ausgabe/formatierung.md
      - Textausgabe: ausgabe/textausgabe.md
  - Objektorientierung:
      - "Objekte und Klassen": objektorientierung/klassen.md
      - Zugriffsmodifikator: objektorientierung/zugriffsmodifikator.md
  - Klassen:
      - Scanner: eingabe/scanner.md
      - Formatierung: ausgabe/formatierung.md
      - StringBuilder: klassen/stringbuilder.md
      - StringTokenizer: klassen/stringtokenizer.md

theme:
  font: false
  name: material
  custom_dir: overrides
  palette:
    primary: grey
  language: de
  features:
    - navigation.sections
    - content.code.annotate
    -
extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/roboto.css

extra_javascript:
  - assets/javascripts/extra.js
  - assets/javascripts/mathjax.js
  - assets/javascripts/polyfill.min.js
  - assets/javascripts/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.magiclink:
      repo_url_shorthand: true
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
