site_name: PR1 Dokumentation
site_author: BD
repo_url: https://github.com/bdwebnet/pr1_doku
edit_uri: edit/main/docs
theme:
  name: material
  custom_dir: overrides
  palette:
    primary: grey
  language: de
  features:
    - navigation.sections
    - content.code.annotate
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - extra_javascripts/extra.js
markdown_extensions:
  - pymdownx.magiclink:
      repo_url_shorthand: true
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
