site_name: PR1 Dokumentation
site_author: BD
copyright: BD
repo_url: https://github.com/bdwebnet/pr1_doku
edit_uri: blob/main/
theme:
  name: material
  custom_dir: overrides
  palette:
    primary: grey
  language: de
  features:
    - navigation.sections
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - extra_javascripts/extra.js
markdown_extensions:
  - pymdownx.magiclink:
      repo_url_shorthand: true
  - attr_list
